### ISSUE TITLE
Does not work with Alfred 3.5 and MacOS High Sierra 10.13

### ISSUE THREAD

**Issue by moored** [jason0x43/alfred-nest#8]
Typing nest and any other command such at temp returns nothing.

**Comment by adamzaninovich** [comment]
I believe I am seeing the same issue on Alfred v3.5 [876] and macOS 10.13 Beta (17A362a). Here is the output from the debug console:

```
Starting debug for 'Nest'

[2017-10-17 21:38:03][ERROR: input.scriptfilter] Code 2: 1969/12/31 16:00:00 Using config file ~/Library/Application Support/Alfred 2/Workflow Data/com.jason0x43.alfred-nest/config.json
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1e5f6e26491 pc=0x19be90]

goroutine 1 [running]:
runtime.throw(0x4556a0, 0x2a)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90 fp=0xc8200d3ae0 sp=0xc8200d3ac8
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8200d3b30 sp=0xc8200d3ae0
sync.(*Pool).Get(0x5b2c60, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/pool.go:101 +0x40 fp=0xc8200d3b80 sp=0xc8200d3b30
fmt.newPrinter(0xc8200f40c0)
	/usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:133 +0x27 fp=0xc8200d3bc0 sp=0xc8200d3b80
fmt.Sprintln(0xc8200d3de8, 0x2, 0x2, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/fmt/print.go:270 +0x28 fp=0xc8200d3c10 sp=0xc8200d3bc0
log.Println(0xc8200d3de8, 0x2, 0x2)
	/usr/local/Cellar/go/1.5.1/libexec/src/log/log.go:295 +0x35 fp=0xc8200d3c58 sp=0xc8200d3c10
main.main()
	/Users/jason/Documents/Programming/go/src/github.com/jason0x43/alfred-nest/main.go:50 +0x652 fp=0xc8200d3f40 sp=0xc8200d3c58
runtime.main()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc8200d3f90 sp=0xc8200d3f40
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200d3f98 sp=0xc8200d3f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1
```

Even though it says `Application Support/Alfred 2`, I am running Alfred v3.5 [876] and macOS 10.13 Beta (17A362a)

**Comment by bkeating** [comment]
Same here as what's shared above. I too have the same version of `go` installed; `1.5` and noticed that brew also offers up a `go@1.8`. Perhaps this is a version thing?

**Comment by chrisrowe** [comment]
+1 digging into this some more

**Comment by bkeating** [comment]
So I checked and I in fact do not even have `go` installed. Nothing exists at `/usr/local/Cellar/go/` so I tried to install it; `1.5.1` just as it is cited in the error above:

```sh
brew install go@1.5
```

I have Alfred3, Xcode (w/Command Line Tools), homebrew is up-to-date... This is the output of installing:

```sh
COMPAQ6:~ bpk$ brew install go@1.5
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://storage.googleapis.com/golang/go1.5.4.src.tar.gz
Already downloaded: /Users/bpk/Library/Caches/Homebrew/go@1.5-1.5.4.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4-bootstrap-20161024.tar.gz
Already downloaded: /Users/bpk/Library/Caches/Homebrew/go@1.5--gobootstrap-20161024.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/bpk/Library/Logs/Homebrew/go@1.5/01.make.bash:
cmd/pprof/internal/report
encoding/csv
encoding/gob
image/gif
image/png
runtime/debug
testing
testing/iotest
testing/quick
text/scanner
cmd/pprof/internal/commands
cmd/pprof/internal/driver
runtime/cgo
# runtime/cgo
clang: error: no such file or directory: '/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin17.3.0/libclang_rt.builtins-x86_64.a'

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

This is quickly getting out of this repo's terroritory but to keep going, I checked and `/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin17.3.0` does not exist. However, `/Library/Developer/CommandLineTools/usr/lib/clang/9.0.0/lib/darwin/` does, but it's missing the file `libclang_rt.builtins-x86_64.a`. I did not have this issue when I tested an install of `brew install go@1.8`, so Im guessing maybe 1.5.1 is just old and citing DEPRECATED resources.

My next step is to `brew install go` and symlink whatever version that gives me to `/user/local/Cellar/go/1.5.1/`

Potentially indirect reference to this issue: https://trac.macports.org/ticket/54797

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “Does not work with Alfred 3.5 and MacOS High Sierra 10.13”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
